### ISSUE TITLE
nvim-todoist/api.lua:3: module 'rapidjson' not found

### ISSUE THREAD

**Issue by kristijanhusak** [smolck/nvim-todoist.lua#2]
There's a dependency on rapidjson, so I think it should be added to readme.

Edit: I'm not sure how to install it. I installed luarocks from aur and installed it with that, but it's not working. Probably mismatching version. Any help is appreciated.

**Comment by smolck** [comment]
@kristijanhusak Should be fixed in https://github.com/smolck/nvim-todoist.lua/commit/e53661363e7e1cce422b996cfeaf65b59088d85a, where I've removed the rapidjson dependency entirely (in exchange for using [json.lua](https://github.com/rxi/json.lua)). Let me know if you have further issues; I'll go ahead and close this.
